"""baseline_schema

Revision ID: 24ddb8900f24
Revises: 
Create Date: 2026-06-29 00:13:29.905515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24ddb8900f24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('telefone_whatsapp', sa.String(), nullable=False),
    sa.Column('telefone_proprietario', sa.String(), nullable=True),
    sa.Column('webhook_token', sa.String(), nullable=False),
    sa.Column('evolution_instance', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('valor_mensalidade', sa.Float(), nullable=True),
    sa.Column('data_expiracao_teste', sa.DateTime(), nullable=True),
    sa.Column('cupom_vendedor', sa.String(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('limite_conversas_mes', sa.Integer(), nullable=True),
    sa.Column('conversas_mes_atual', sa.Integer(), nullable=True),
    sa.Column('data_reset_contador', sa.DateTime(), nullable=True),
    sa.Column('tokens_input_mes', sa.Integer(), nullable=True),
    sa.Column('tokens_output_mes', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('etapas_funil', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nicho', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evolution_instance'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('telefone_whatsapp'),
    sa.UniqueConstraint('webhook_token')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_nicho', sa.String(), nullable=False),
    sa.Column('prompt_sistema', sa.Text(), nullable=False),
    sa.Column('tom_voz', sa.Text(), nullable=True),
    sa.Column('missao', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('etapas_funil', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nicho', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_nicho')
    )
    op.create_table('bloqueios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fim', sa.String(length=5), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campanhas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('codigo_ref', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanhas_codigo_ref'), 'campanhas', ['codigo_ref'], unique=True)
    op.create_table('campos_customizados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('opcoes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('dependencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardapio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunicados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('imagem_url', sa.Text(), nullable=True),
    sa.Column('data_programada', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_membros', sa.Integer(), nullable=True),
    sa.Column('enviados', sa.Integer(), nullable=True),
    sa.Column('erros', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('disponibilidade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('data_especifica', sa.String(length=10), nullable=True),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fim', sa.String(length=5), nullable=False),
    sa.Column('intervalo_min', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_legais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('fonte', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas_clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('regime_tributario', sa.String(), nullable=True),
    sa.Column('contato_nome', sa.String(), nullable=True),
    sa.Column('contato_telefone', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_auxiliar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('estado_json', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('visit_offer_made', sa.Boolean(), nullable=True),
    sa.Column('utm_source', sa.String(length=50), nullable=True),
    sa.Column('utm_campaign', sa.String(length=50), nullable=True),
    sa.Column('canal_entrada', sa.String(length=50), nullable=True),
    sa.Column('dados_customizados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listas_transmissao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membros_academia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('plano_nome', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('aviso_7_dias_enviado', sa.Boolean(), nullable=True),
    sa.Column('aviso_3_dias_enviado', sa.Boolean(), nullable=True),
    sa.Column('aviso_vencido_enviado', sa.Boolean(), nullable=True),
    sa.Column('importado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('tem_variacao_caracteristica', sa.Boolean(), nullable=True),
    sa.Column('caracteristicas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorrencia_sugerida_dias', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transbordo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('servico_id', sa.UUID(), nullable=True),
    sa.Column('servico_nome', sa.String(), nullable=False),
    sa.Column('servico_duracao', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fim', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('lembrete_cliente_enviado', sa.Boolean(), nullable=True),
    sa.Column('lembrete_profissional_enviado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_agencia_viagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('canal_entrada', sa.String(), nullable=True),
    sa.Column('destinos_interesse', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codigos_recuperacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunicado_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comunicado_id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comunicado_id'], ['comunicados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disparos_lista',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lista_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('imagem_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_contatos', sa.Integer(), nullable=True),
    sa.Column('enviados', sa.Integer(), nullable=True),
    sa.Column('erros', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('data_programada', sa.DateTime(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_transmissao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads_seguro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('nome_contato', sa.String(length=200), nullable=True),
    sa.Column('nome_segurado', sa.String(length=200), nullable=True),
    sa.Column('relacao_segurado', sa.String(length=50), nullable=True),
    sa.Column('tipo_seguro', sa.String(length=30), nullable=True),
    sa.Column('produto_especifico', sa.String(length=100), nullable=True),
    sa.Column('idade_segurado', sa.Integer(), nullable=True),
    sa.Column('tem_cnpj', sa.Boolean(), nullable=True),
    sa.Column('e_mei', sa.Boolean(), nullable=True),
    sa.Column('tem_plano_anterior', sa.Boolean(), nullable=True),
    sa.Column('plano_anterior_nome', sa.String(length=100), nullable=True),
    sa.Column('mais_de_6_meses', sa.Boolean(), nullable=True),
    sa.Column('regiao', sa.String(length=200), nullable=True),
    sa.Column('hospitais_preferidos', sa.Text(), nullable=True),
    sa.Column('marca_modelo', sa.String(length=100), nullable=True),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('cep_pernoite', sa.String(length=10), nullable=True),
    sa.Column('uso_veiculo', sa.String(length=30), nullable=True),
    sa.Column('tem_garagem', sa.Boolean(), nullable=True),
    sa.Column('condutor_principal', sa.String(length=200), nullable=True),
    sa.Column('idade_condutor', sa.Integer(), nullable=True),
    sa.Column('bonus_classe', sa.Integer(), nullable=True),
    sa.Column('tipo_imovel', sa.String(length=30), nullable=True),
    sa.Column('cep_imovel', sa.String(length=10), nullable=True),
    sa.Column('metragem', sa.Integer(), nullable=True),
    sa.Column('imovel_proprio', sa.Boolean(), nullable=True),
    sa.Column('docs_recebidos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('docs_pendentes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('canal_entrada', sa.String(length=20), nullable=True),
    sa.Column('template_raw', sa.Text(), nullable=True),
    sa.Column('resumo_ia', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('seguradora_escolhida', sa.String(length=100), nullable=True),
    sa.Column('valor_proposta', sa.Float(), nullable=True),
    sa.Column('data_proposta_enviada', sa.DateTime(), nullable=True),
    sa.Column('data_vencimento_apolice', sa.DateTime(), nullable=True),
    sa.Column('numero_apolice', sa.String(length=100), nullable=True),
    sa.Column('ultimo_followup_em', sa.DateTime(), nullable=True),
    sa.Column('followup_count', sa.Integer(), nullable=True),
    sa.Column('motivo_perda', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('data_flexivel', sa.Boolean(), nullable=True),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notificado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listas_transmissao_contatos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lista_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_transmissao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('intencao', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obrigacoes_fiscais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('empresa_cliente_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prazo', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('aviso_enviado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_cliente_id'], ['empresas_clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('numero_pedido', sa.Integer(), nullable=True),
    sa.Column('modo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('nome_balcao', sa.String(), nullable=True),
    sa.Column('numero_mesa', sa.Integer(), nullable=True),
    sa.Column('avaliacao_nota', sa.Integer(), nullable=True),
    sa.Column('avaliacao_comentario', sa.Text(), nullable=True),
    sa.Column('pagamento_status', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_recorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('intervalo_dias', sa.Integer(), nullable=False),
    sa.Column('ultimo_agendamento', sa.String(length=10), nullable=False),
    sa.Column('proximo_sugerido', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_seguro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=300), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.Column('ocr_processado', sa.Boolean(), nullable=True),
    sa.Column('ocr_resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_confianca', sa.Float(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_seguro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followup_delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('agendado_para', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followups_seguro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads_seguro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=True),
    sa.Column('servico_nome', sa.String(), nullable=False),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('cardapio_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco_unit', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('itens_agendamento')
    op.drop_table('followups_seguro')
    op.drop_table('followup_delivery')
    op.drop_table('documentos_seguro')
    op.drop_table('series_recorrencia')
    op.drop_table('pedidos')
    op.drop_table('obrigacoes_fiscais')
    op.drop_table('mensagens')
    op.drop_table('listas_transmissao_contatos')
    op.drop_table('lista_espera')
    op.drop_table('leads_seguro')
    op.drop_table('eventos')
    op.drop_table('disparos_lista')
    op.drop_table('comunicado_logs')
    op.drop_table('codigos_recuperacao')
    op.drop_table('clientes_agencia_viagens')
    op.drop_table('agendamentos')
    op.drop_table('usuarios')
    op.drop_table('transbordo')
    op.drop_table('servicos')
    op.drop_table('membros_academia')
    op.drop_table('listas_transmissao')
    op.drop_table('leads')
    op.drop_table('estado_auxiliar')
    op.drop_table('empresas_clientes')
    op.drop_table('documentos_legais')
    op.drop_table('disponibilidade')
    op.drop_table('configuracoes')
    op.drop_table('comunicados')
    op.drop_table('cardapio')
    op.drop_table('campos_customizados')
    op.drop_index(op.f('ix_campanhas_codigo_ref'), table_name='campanhas')
    op.drop_table('campanhas')
    op.drop_table('bloqueios')
    op.drop_table('prompt_templates')
    op.drop_table('empresas')
    # ### end Alembic commands ###
